import {
  UserProfile,
  Vendor,
  VendorApplication,
  Category,
  Meal,
  Order,
  NotificationItem,
  OrderStatusHistory,
  Review,
  RiderProfile,
} from '../types';

export const INITIAL_PROFILES: UserProfile[] = [
  {
    id: 'user-student-1',
    full_name: 'David Ayantade',
    email: 'student@campusbites.edu',
    phone: '+234 801 234 5678',
    role: 'STUDENT',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'user-rider-1',
    full_name: 'Tunde Bakare',
    email: 'rider@campusbites.edu',
    phone: '+234 812 345 6789',
    role: 'RIDER',
    profile_image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-05T08:00:00Z',
  },
  {
    id: 'user-vendor-1',
    full_name: 'Mama Cass Owner',
    email: 'mamacass@campusbites.edu',
    phone: '+234 802 345 6789',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-02T09:00:00Z',
  },
  {
    id: 'user-vendor-2',
    full_name: 'Buka Chief',
    email: 'bukaexpress@campusbites.edu',
    phone: '+234 803 456 7890',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-03T11:30:00Z',
  },
  {
    id: 'user-vendor-3',
    full_name: 'Campus Grills Admin',
    email: 'campusgrills@campusbites.edu',
    phone: '+234 804 567 8901',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-04T14:15:00Z',
  },
  {
    id: 'user-vendor-4',
    full_name: 'Delight Bakery Admin',
    email: 'delightbakery@campusbites.edu',
    phone: '+234 805 678 9012',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-04T16:00:00Z',
  },
  {
    id: 'user-vendor-5',
    full_name: 'Iya Basira Admin',
    email: 'iyabasira@campusbites.edu',
    phone: '+234 806 789 0123',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-05T09:30:00Z',
  },
  {
    id: 'user-vendor-6',
    full_name: 'Tropics Hub Admin',
    email: 'tropicshub@campusbites.edu',
    phone: '+234 807 890 1234',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-05T12:00:00Z',
  },
  {
    id: 'user-applicant-7',
    full_name: 'Kareem Balogun',
    email: 'kareem.suya@campusbites.edu',
    phone: '+234 809 111 2233',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-12T14:30:00Z',
  },
  {
    id: 'user-applicant-8',
    full_name: 'Chinedu Okonkwo',
    email: 'chinedu.wok@campusbites.edu',
    phone: '+234 810 222 3344',
    role: 'VENDOR',
    profile_image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-08-13T09:15:00Z',
  },
  {
    id: 'user-admin-1',
    full_name: 'System Administrator',
    email: 'admin@campusbites.edu',
    phone: '+234 800 000 0000',
    role: 'ADMIN',
    profile_image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    created_at: '2026-07-15T08:00:00Z',
  },
];

export const INITIAL_RIDERS: RiderProfile[] = [
  {
    id: 'rider-1',
    user_id: 'user-rider-1',
    full_name: 'Tunde Bakare',
    phone: '+234 812 345 6789',
    email: 'rider@campusbites.edu',
    profile_image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=250&q=80',
    vehicle_type: 'BICYCLE',
    vehicle_plate: 'CAMPUS-ECO-042',
    campus_zone: 'All Campus Zones',
    is_online: true,
    rating: 4.9,
    total_deliveries: 48,
    today_deliveries: 4,
    total_earnings: 24500,
    today_earnings: 2200,
    wallet_balance: 14200,
    created_at: '2026-08-05T08:00:00Z',
  },
];

import jollofRiceImg from '../assets/images/jollof_rice_1786625986094.jpg';
import amalaSoupImg from '../assets/images/amala_soup_1786625999578.jpg';
import poundedYamImg from '../assets/images/pounded_yam_egusi_1786626012604.jpg';
import suyaBoliImg from '../assets/images/beef_suya_boli_1786626023704.jpg';
import shawarmaImg from '../assets/images/chicken_shawarma_1786626039847.jpg';
import meatPieImg from '../assets/images/beef_meat_pie_1786626052754.jpg';
import friedRiceImg from '../assets/images/nigerian_fried_rice_1786626063642.jpg';
import zoboDrinkImg from '../assets/images/zobo_hibiscus_drink_1786626077664.jpg';
import maltinaCanImg from '../assets/images/maltina_can_1786626963944.jpg';
import yellowEbaOkroImg from '../assets/images/yellow_eba_okro_1786626978764.jpg';
import semoOgbonoImg from '../assets/images/semo_ogbono_1786626990518.jpg';
import ayamaseOfadaImg from '../assets/images/ayamase_ofada_1786627002464.jpg';
import cocaColaImg from '../assets/images/coca_cola_1786627016370.jpg';
import fantaOrangeImg from '../assets/images/fanta_orange_1786627029497.jpg';
import pepsiColaImg from '../assets/images/pepsi_cola_1786627040408.jpg';
import spriteDrinkImg from '../assets/images/sprite_drink_1786627055889.jpg';
import evaWaterImg from '../assets/images/eva_water_1786627068471.jpg';
import puffPuffImg from '../assets/images/puff_puff_1786627081500.jpg';
import moiMoiImg from '../assets/images/moi_moi_1786627094143.jpg';
import asunGoatImg from '../assets/images/asun_goat_1786627105055.jpg';
import pepperedChickenImg from '../assets/images/peppered_chicken_1786627116504.jpg';
import sausageRollImg from '../assets/images/sausage_roll_1786627130564.jpg';
import ewaAganyinImg from '../assets/images/ewa_aganyin_dodo_1786681507247.jpg';
import catfishPepperSoupImg from '../assets/images/catfish_pepper_soup_1786681518573.jpg';
import afangSoupImg from '../assets/images/afang_soup_swallow_1786681531076.jpg';
import gizdodoImg from '../assets/images/gizdodo_plantain_gizzard_1786681542208.jpg';
import boliGrilledFishImg from '../assets/images/boli_grilled_fish_1786681552486.jpg';
import nativeJollofImg from '../assets/images/native_jollof_rice_1786681567135.jpg';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Rice Dishes', description: 'Party Jollof, Fried Rice, Ofada & Native Village Rice', icon_name: 'Utensils', meal_count: 10 },
  { id: 'cat-2', name: 'Swallow & Soups', description: 'Hot Amala, Pounded Yam, Eba, Afang, Egusi & Okro', icon_name: 'Soup', meal_count: 10 },
  { id: 'cat-3', name: 'Grills & Shawarma', description: 'Grilled Fish & Boli, Shawarma, Suya, Peppered Chicken & Asun', icon_name: 'Flame', meal_count: 8 },
  { id: 'cat-4', name: 'Native & Beans', description: 'Ewa Aganyin + Dodo, Gizdodo, Catfish Pepper Soup & Moi Moi', icon_name: 'Flame', meal_count: 6 },
  { id: 'cat-5', name: 'Snacks & Pastries', description: 'Nigerian Meat Pies, Puff Puff, Sausage Rolls', icon_name: 'Cookie', meal_count: 6 },
  { id: 'cat-6', name: 'Cold Drinks & Water', description: 'Maltina, Zobo, Coke, Fanta, Pepsi, Sprite & Table Water', icon_name: 'CupSoda', meal_count: 12 },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    owner_id: 'user-vendor-1',
    business_name: 'Mama Cass Kitchen',
    description: 'Authentic African & Continental campus meals prepared fresh daily with premium ingredients.',
    phone: '+234 802 345 6789',
    location_type: 'CAMPUS',
    address: 'Student Union Building (SUB), Block B, Shop 12',
    location_description: 'Opposite Main Auditorium, Ground Floor',
    verification_status: 'APPROVED',
    approval_timestamp: '2026-08-02T10:00:00Z',
    approved_by: 'user-admin-1',
    banner_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    total_orders: 142,
    created_at: '2026-08-02T09:00:00Z',
  },
  {
    id: 'vendor-2',
    owner_id: 'user-vendor-2',
    business_name: 'Buka Express',
    description: 'Hot Amala, Pounded Yam, Gbegiri & Ewedu served piping hot with assorted meat and fish.',
    phone: '+234 803 456 7890',
    location_type: 'CAMPUS',
    address: 'Faculty of Technology Food Court, Stand 4',
    location_description: 'Beside Engineering Lecture Theatre',
    verification_status: 'APPROVED',
    approval_timestamp: '2026-08-03T12:00:00Z',
    approved_by: 'user-admin-1',
    banner_image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    total_orders: 215,
    created_at: '2026-08-03T11:30:00Z',
  },
  {
    id: 'vendor-3',
    owner_id: 'user-vendor-3',
    business_name: 'Campus Grills & Shawarma',
    description: 'Juicy chicken shawarma, grilled suya, roasted plantain (Boli) and ice-cold smoothies.',
    phone: '+234 804 567 8901',
    location_type: 'OFF_CAMPUS',
    address: 'Campus Gate 1 Extension, Road 3, Shop 5',
    location_description: 'Adjacent to First Bank ATM Gallery',
    verification_status: 'APPROVED',
    approval_timestamp: '2026-08-04T15:00:00Z',
    approved_by: 'user-admin-1',
    banner_image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    total_orders: 188,
    created_at: '2026-08-04T14:15:00Z',
  },
  {
    id: 'vendor-4',
    owner_id: 'user-vendor-4',
    business_name: 'Delight Bakery & Café',
    description: 'Freshly baked pastries, gourmet meat pies, iced kunu, puff puff, and custom student celebration cakes.',
    phone: '+234 805 678 9012',
    location_type: 'CAMPUS',
    address: 'Postgraduate Hall Complex, Kiosk 2',
    location_description: 'Near PG Library & Hezekiah Annex',
    verification_status: 'APPROVED',
    approval_timestamp: '2026-08-05T10:00:00Z',
    approved_by: 'user-admin-1',
    banner_image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    total_orders: 96,
    created_at: '2026-08-05T09:30:00Z',
  },
  {
    id: 'vendor-5',
    owner_id: 'user-vendor-5',
    business_name: 'Iya Basira Heritage Kitchen',
    description: 'Authentic local Ibadan amala, steaming Abula, pounded yam, semovita with rich Ogbono & goat meat.',
    phone: '+234 807 890 1234',
    location_type: 'CAMPUS',
    address: 'Male Hostels Quad, Mellanby Court Stand 1',
    location_description: 'Between Angola and Mozambique Quad',
    verification_status: 'APPROVED',
    approval_timestamp: '2026-08-06T11:00:00Z',
    approved_by: 'user-admin-1',
    banner_image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    total_orders: 312,
    created_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'vendor-6',
    owner_id: 'user-vendor-6',
    business_name: 'Tropics Fresh & Healthy Hub',
    description: 'Cold-pressed zobo, natural tiger nut milk (kunu aya), yogurt parfaits, fresh fruit smoothies, and steamed moi moi.',
    phone: '+234 808 901 2345',
    location_type: 'CAMPUS',
    address: 'Female Hostels Complex, Awo Hall Pavilion',
    location_description: 'Adjacent to Moremi Hall Walkway',
    verification_status: 'APPROVED',
    approval_timestamp: '2026-08-07T14:00:00Z',
    approved_by: 'user-admin-1',
    banner_image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    total_orders: 145,
    created_at: '2026-08-07T13:30:00Z',
  },
];

export const INITIAL_VENDOR_APPLICATIONS: VendorApplication[] = [
  {
    id: 'app-1',
    applicant_id: 'user-applicant-7',
    applicant_name: 'Kareem Balogun',
    applicant_email: 'kareem.suya@campusbites.edu',
    business_name: "King's Charcoal Suya Lounge",
    description: 'Northern spiced beef and chicken suya, grilled kidney, and sweet roasted corn.',
    phone: '+234 809 111 2233',
    location_type: 'OFF_CAMPUS',
    address: 'Campus Main Gate, Road 1 Commercial Block',
    location_description: 'Near Zenith Bank ATM',
    supporting_info: 'CAC Business Registration #RC-983102. Campus Health Inspection Cleared.',
    verification_status: 'PENDING',
    created_at: '2026-08-12T14:30:00Z',
  },
  {
    id: 'app-2',
    applicant_id: 'user-applicant-8',
    applicant_name: 'Chinedu Okonkwo',
    applicant_email: 'chinedu.wok@campusbites.edu',
    business_name: 'Campus Wok & Asian Noodles',
    description: 'Stir-fry spicy egg noodles, Singapore noodles, spring rolls, and chicken wings.',
    phone: '+234 810 222 3344',
    location_type: 'CAMPUS',
    address: 'Faculty of Pharmacy Cafeteria, Stand 2',
    location_description: 'Ground Floor, Pharmacy Complex',
    supporting_info: 'Food Handling & Safety Certificate #PHARM-2026-044.',
    verification_status: 'PENDING',
    created_at: '2026-08-13T09:15:00Z',
  },
];

export const INITIAL_MEALS: Meal[] = [
  // ==========================================
  // VENDOR 1: MAMA CASS KITCHEN (SUB Block B)
  // ==========================================
  {
    id: 'meal-1',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-1',
    category_name: 'Rice Dishes',
    name: 'Smokey Party Jollof Rice + Peppered Chicken & Dodo',
    description: 'Firewood smoked Nigerian party jollof rice served with ripe fried plantain (dodo), boiled egg, and spicy peppered quarter chicken.',
    price: 2200,
    image_url: jollofRiceImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T10:30:00Z',
  },
  {
    id: 'meal-2',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-1',
    category_name: 'Rice Dishes',
    name: 'Special Fried Rice with Crispy Turkey',
    description: 'Seasoned rice tossed with liver, sweetcorn, green peas & carrots, served with fried golden turkey and dodo.',
    price: 2800,
    image_url: friedRiceImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T10:45:00Z',
  },
  {
    id: 'meal-3',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-1',
    category_name: 'Rice Dishes',
    name: 'White Rice with Ayamase (Ofada Stew) & Assorted Meat',
    description: 'Steamed rice served with bleached-palm-oil green pepper Ayamase stew, boiled egg, and diced assorted meat.',
    price: 2500,
    image_url: ayamaseOfadaImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:00:00Z',
  },
  {
    id: 'meal-10',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-1',
    category_name: 'Rice Dishes',
    name: 'Native Village Jollof Rice (Iwuk Edesi)',
    description: 'Slow-cooked native palm oil rice prepared with smoked catfish flakes, locust beans (iru), diced kpomo, crayfish, and fragrant scent leaves.',
    price: 2400,
    image_url: nativeJollofImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:05:00Z',
  },
  {
    id: 'meal-11',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-4',
    category_name: 'Native & Beans',
    name: 'Ewa Aganyin + Fried Plantain (Dodo) & Agege Bread',
    description: 'Authentic mashed honey beans drenched in fiery slow-caramelized onion and pepper aganyin oil, served with ripe fried dodo and soft Agege bread.',
    price: 1800,
    image_url: ewaAganyinImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:10:00Z',
  },
  {
    id: 'meal-12',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-4',
    category_name: 'Native & Beans',
    name: 'Gizdodo (Peppered Chicken Gizzards & Sweet Dodo)',
    description: 'Tender seasoned chicken gizzards and sweet fried ripe plantain cubes sautéed in fresh red bell pepper, habanero, and sweet onion relish.',
    price: 2200,
    image_url: gizdodoImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:12:00Z',
  },
  {
    id: 'meal-101',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-5',
    category_name: 'Snacks & Pastries',
    name: 'Gourmet Beef Meat Pie',
    description: 'Flaky baked pastry filled with seasoned minced beef, potatoes and carrots.',
    price: 600,
    image_url: meatPieImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:15:00Z',
  },
  // Mama Cass Drinks & Water
  {
    id: 'drink-101',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Coca-Cola (50cl Pet Bottle)',
    description: 'Ice-cold original Coca-Cola soft drink bottle.',
    price: 350,
    image_url: cocaColaImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:30:00Z',
  },
  {
    id: 'drink-102',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Fanta Orange (50cl Pet Bottle)',
    description: 'Refreshing fruity orange soft drink served cold.',
    price: 350,
    image_url: fantaOrangeImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:35:00Z',
  },
  {
    id: 'drink-103',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Cold Maltina Canned Drink (33cl)',
    description: 'Premium rich non-alcoholic malt drink.',
    price: 500,
    image_url: maltinaCanImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:40:00Z',
  },
  {
    id: 'drink-104',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Eva Premium Bottled Water (75cl)',
    description: 'Purified, ice-chilled spring drinking water.',
    price: 250,
    image_url: evaWaterImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-02T11:45:00Z',
  },

  // ==========================================
  // VENDOR 2: BUKA EXPRESS (Tech Food Court)
  // ==========================================
  {
    id: 'meal-4',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Hot Abula Special (Amala + Gbegiri + Ewedu + Goat Meat)',
    description: 'Authentic dark Oyo Amala served piping hot with smooth bean Gbegiri, green Ewedu, spicy buka stew, and tender goat meat.',
    price: 2500,
    image_url: amalaSoupImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T12:30:00Z',
  },
  {
    id: 'meal-5',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Pounded Yam + Rich Egusi Soup & Assorted Meat',
    description: 'Soft fluffy pounded yam paired with melon egusi soup cooked with stockfish, kpomo, shaki, and beef.',
    price: 2800,
    image_url: poundedYamImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:00:00Z',
  },
  {
    id: 'meal-13',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Calabar Afang Soup + Pounded Yam & Goat Meat',
    description: 'Rich thick shredded afang leaves and fresh waterleaf soup cooked with dried fish, sea periwinkles, kpomo, and tender goat meat.',
    price: 2800,
    image_url: afangSoupImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:05:00Z',
  },
  {
    id: 'meal-201',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Yellow Eba + Seafood Okro Soup & Peppered Fish',
    description: 'Ijebu garri eba served with diced fresh okro soup, prawns, stockfish, and a whole peppered croaker fish.',
    price: 2200,
    image_url: yellowEbaOkroImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:10:00Z',
  },
  {
    id: 'meal-202',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Semo + Ogbono Soup & Beef',
    description: 'Smooth semovita served with thick draw Ogbono soup packed with beef and dried catfish.',
    price: 2000,
    image_url: semoOgbonoImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:20:00Z',
  },
  {
    id: 'meal-14',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-4',
    category_name: 'Native & Beans',
    name: 'Fresh Catfish Pepper Soup (Point & Kill)',
    description: 'Steaming hot aromatic herbal broth cooked with fresh river catfish chunks, scent leaves, utazi, and authentic calabash nutmeg spices.',
    price: 3000,
    image_url: catfishPepperSoupImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:25:00Z',
  },
  // Buka Express Drinks & Water
  {
    id: 'meal-6',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Special Zobo Drink with Ginger & Pineapple (500ml)',
    description: 'House-brewed hibiscus tea spiced with ginger, clove, fresh pineapple juice and served ice-cold.',
    price: 500,
    image_url: zoboDrinkImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:15:00Z',
  },
  {
    id: 'drink-201',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Pepsi Cola (50cl Pet Bottle)',
    description: 'Cold crisp Pepsi cola bottle.',
    price: 350,
    image_url: pepsiColaImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:30:00Z',
  },
  {
    id: 'drink-202',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Cold Amstel Malta Can (33cl)',
    description: 'Chilled low-sugar nourishing malt drink.',
    price: 500,
    image_url: maltinaCanImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:35:00Z',
  },
  {
    id: 'drink-203',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Cway Chilled Pure Table Water (75cl)',
    description: 'Ice-cold bottled pure drinking water.',
    price: 250,
    image_url: evaWaterImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-03T13:40:00Z',
  },

  // ==========================================
  // VENDOR 3: CAMPUS GRILLS & SHAWARMA (Gate 1)
  // ==========================================
  {
    id: 'meal-7',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-3',
    category_name: 'Grills & Shawarma',
    name: 'Double Sausage Chicken Shawarma + Extra Cheese',
    description: 'Loaded toasted pita flatbread wrap with grilled chicken strips, double hotdog sausages, garlic mayo, cabbage, and melted cheese.',
    price: 2500,
    image_url: shawarmaImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T15:30:00Z',
  },
  {
    id: 'meal-8',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-3',
    category_name: 'Grills & Shawarma',
    name: 'Spicy Beef Suya + Roasted Plantain (Boli)',
    description: 'Charcoal grilled spicy beef suya seasoned with Yaji pepper, served with sliced onions, tomatoes, and roasted ripe plantain.',
    price: 2200,
    image_url: suyaBoliImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:00:00Z',
  },
  {
    id: 'meal-15',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-3',
    category_name: 'Grills & Shawarma',
    name: 'Charcoal Grilled Whole Fish + Boli (Roasted Plantain)',
    description: 'Whole fresh croaker fish seasoned in spicy suya pepper and flame-grilled over charcoal, served with roasted sweet ripe plantain, pepper sauce, and sliced onions.',
    price: 3500,
    image_url: boliGrilledFishImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:05:00Z',
  },
  {
    id: 'meal-301',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-3',
    category_name: 'Grills & Shawarma',
    name: 'Full Grilled Peppered Chicken Quarter',
    description: 'Succulent chicken quarter marinated in northern suya spices and flame-grilled over open coals.',
    price: 2000,
    image_url: pepperedChickenImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:15:00Z',
  },
  {
    id: 'meal-302',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-3',
    category_name: 'Grills & Shawarma',
    name: 'Spicy Goat Meat Asun (Plate)',
    description: 'Tender diced goat meat tossed in hot habanero pepper, onions, and local aromatic spices.',
    price: 2500,
    image_url: asunGoatImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:30:00Z',
  },
  // Campus Grills Drinks & Water
  {
    id: 'drink-301',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Sprite Lemon-Lime (50cl Pet Bottle)',
    description: 'Refreshing lemon-lime clear soda.',
    price: 350,
    image_url: spriteDrinkImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:40:00Z',
  },
  {
    id: 'drink-302',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chivita 100% Pineapple Juice (315ml)',
    description: 'Pure 100% natural fruit juice without added sugar.',
    price: 600,
    image_url: zoboDrinkImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:45:00Z',
  },
  {
    id: 'drink-303',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Nestle Pure Life Bottled Water (75cl)',
    description: 'Ice-cold table water bottle.',
    price: 250,
    image_url: evaWaterImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-04T16:50:00Z',
  },

  // ==========================================
  // VENDOR 4: DELIGHT BAKERY & CAFÉ (PG Hall Kiosk)
  // ==========================================
  {
    id: 'meal-401',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-5',
    category_name: 'Snacks & Pastries',
    name: 'Gourmet Nigerian Beef Meat Pie',
    description: 'Flaky baked buttery crust packed with rich seasoned minced beef, carrots, and potatoes.',
    price: 600,
    image_url: meatPieImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:20:00Z',
  },
  {
    id: 'meal-402',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-5',
    category_name: 'Snacks & Pastries',
    name: 'Fresh Golden Puff Puff Pack (6 pcs)',
    description: 'Warm, fluffy, sweet deep-fried dough balls fried fresh hourly.',
    price: 400,
    image_url: puffPuffImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:25:00Z',
  },
  {
    id: 'meal-403',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-5',
    category_name: 'Snacks & Pastries',
    name: 'Jumbo Chicken Sausage Roll',
    description: 'Baked puff pastry roll with seasoned chicken sausage filling.',
    price: 500,
    image_url: sausageRollImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:30:00Z',
  },
  {
    id: 'meal-404',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-4',
    category_name: 'Native & Beans',
    name: 'Steamed Bean Cake (Moi Moi Elemi Meji)',
    description: 'Traditional steamed peeled bean pudding made with boiled egg, fish, and red bell peppers.',
    price: 700,
    image_url: moiMoiImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:35:00Z',
  },
  // Delight Bakery Drinks & Water
  {
    id: 'drink-401',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Fresh Chilled Tiger Nut Drink / Kunu (500ml)',
    description: '100% natural blend of tiger nuts, dates, coconut, and ginger served ice-cold.',
    price: 600,
    image_url: zoboDrinkImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:40:00Z',
  },
  {
    id: 'drink-402',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Fanta Orange (50cl Pet Bottle)',
    description: 'Fruity cold orange soft drink.',
    price: 350,
    image_url: fantaOrangeImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:45:00Z',
  },
  {
    id: 'drink-403',
    vendor_id: 'vendor-4',
    vendor_name: 'Delight Bakery & Café',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Eva Premium Bottled Water (75cl)',
    description: 'Ice-cold table water.',
    price: 250,
    image_url: evaWaterImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-10T16:50:00Z',
  },

  // ==========================================
  // VENDOR 5: IYA BASIRA HERITAGE KITCHEN (Mellanby Court)
  // ==========================================
  {
    id: 'meal-501',
    vendor_id: 'vendor-5',
    vendor_name: 'Iya Basira Heritage Kitchen',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Iya Basira Hot Abula Amala with Goat Meat & Opon',
    description: 'Authentic piping hot Oyo-style dark yam flour amala served with smooth yellow gbegiri, frothy green ewedu, and tender spiced goat meat.',
    price: 2400,
    image_url: amalaSoupImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-06T10:00:00Z',
  },
  {
    id: 'meal-502',
    vendor_id: 'vendor-5',
    vendor_name: 'Iya Basira Heritage Kitchen',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Pounded Yam with Rich Ogbono & Okro Soup + Kpomo',
    description: 'Smooth stretchy pounded yam served with thick aromatic ogbono soup, fresh sliced okro, tender soft kpomo, and dry fish flakes.',
    price: 2500,
    image_url: semoOgbonoImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-06T10:15:00Z',
  },
  {
    id: 'meal-503',
    vendor_id: 'vendor-5',
    vendor_name: 'Iya Basira Heritage Kitchen',
    category_id: 'cat-2',
    category_name: 'Swallow & Soups',
    name: 'Yellow Garri Eba with Egusi Soup & Fried Panla Fish',
    description: 'Freshly stirred yellow cassava eba with rich lumpy melon seed egusi soup, ugwu leaves, and crispy fried fish.',
    price: 2100,
    image_url: yellowEbaOkroImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-06T10:30:00Z',
  },
  {
    id: 'meal-504',
    vendor_id: 'vendor-5',
    vendor_name: 'Iya Basira Heritage Kitchen',
    category_id: 'cat-1',
    category_name: 'Rice Dishes',
    name: 'Ofada Rice & Hot Ayamase Designer Stew',
    description: 'Unpolished traditional ofada rice served with pungent bleached palm oil green pepper sauce, boiled egg, diced offals, and iru locust beans.',
    price: 2600,
    image_url: ayamaseOfadaImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-06T10:45:00Z',
  },
  {
    id: 'drink-501',
    vendor_id: 'vendor-5',
    vendor_name: 'Iya Basira Heritage Kitchen',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Iya Basira Special Spiced Zobo Drink (500ml)',
    description: 'Rich chilled hibiscus flower drink sweetened with fresh dates, cloves, ginger, and pineapple.',
    price: 500,
    image_url: zoboDrinkImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-06T11:00:00Z',
  },
  {
    id: 'drink-502',
    vendor_id: 'vendor-5',
    vendor_name: 'Iya Basira Heritage Kitchen',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Cold Maltina Canned Drink (33cl)',
    description: 'Chilled premium malt beverage.',
    price: 450,
    image_url: maltinaCanImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-06T11:05:00Z',
  },

  // ==========================================
  // VENDOR 6: TROPICS FRESH & HEALTHY HUB (Awo Hall)
  // ==========================================
  {
    id: 'meal-601',
    vendor_id: 'vendor-6',
    vendor_name: 'Tropics Fresh & Healthy Hub',
    category_id: 'cat-4',
    category_name: 'Native & Beans',
    name: 'Steamed Moi Moi Special with Boiled Egg & Flaked Fish',
    description: 'Steamed bean pudding wrapped in local leaves, cooked with whole boiled egg, flaked mackerel, and red bell peppers.',
    price: 700,
    image_url: moiMoiImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-07T13:30:00Z',
  },
  {
    id: 'meal-602',
    vendor_id: 'vendor-6',
    vendor_name: 'Tropics Fresh & Healthy Hub',
    category_id: 'cat-5',
    category_name: 'Snacks & Pastries',
    name: 'Warm Puff Puff Box (8 pcs) with Honey Drizzle',
    description: 'Golden fried fluffy dough balls served fresh with sweet natural honey drizzle.',
    price: 500,
    image_url: puffPuffImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-07T13:45:00Z',
  },
  {
    id: 'drink-601',
    vendor_id: 'vendor-6',
    vendor_name: 'Tropics Fresh & Healthy Hub',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Natural Tiger Nut Milk Drink (Kunu Aya 500ml)',
    description: 'Chilled fresh blend of tiger nuts, dried dates, coconut, and ginger. 100% dairy-free and refreshing.',
    price: 700,
    image_url: zoboDrinkImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-07T14:00:00Z',
  },
  {
    id: 'drink-602',
    vendor_id: 'vendor-6',
    vendor_name: 'Tropics Fresh & Healthy Hub',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Chilled Coca-Cola (50cl Pet Bottle)',
    description: 'Cold crisp refreshing Coca-Cola.',
    price: 350,
    image_url: cocaColaImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-07T14:05:00Z',
  },
  {
    id: 'drink-603',
    vendor_id: 'vendor-6',
    vendor_name: 'Tropics Fresh & Healthy Hub',
    category_id: 'cat-6',
    category_name: 'Cold Drinks & Water',
    name: 'Eva Premium Bottled Water (75cl)',
    description: 'Ice-cold pure table water.',
    price: 250,
    image_url: evaWaterImg,
    availability: 'AVAILABLE',
    created_at: '2026-08-07T14:10:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    student_id: 'user-student-1',
    student_name: 'David Ayantade',
    student_phone: '+234 801 234 5678',
    order_reference: 'CB-2026-8910',
    fulfillment_method: 'DELIVERY',
    total_amount: 4300,
    delivery_fee: 500,
    delivery_otp: '7429',
    status: 'PREPARING',
    created_at: '2026-08-13T03:15:00Z',
    updated_at: '2026-08-13T03:30:00Z',
    delivery_details: {
      delivery_location: 'Fajuyi Hall of Residence, Block B, Room 204',
      location_description: '2nd Floor, Left Wing near stairs',
      contact_phone: '+234 801 234 5678',
      delivery_instructions: 'Please call when you reach Fajuyi Gate.',
    },
    vendor_orders: [
      {
        id: 'vord-1001-A',
        parent_order_id: 'ord-1001',
        vendor_id: 'vendor-1',
        vendor_name: 'Mama Cass Kitchen',
        status: 'PREPARING',
        subtotal: 1800,
        created_at: '2026-08-13T03:15:00Z',
        items: [
          {
            id: 'item-1',
            vendor_order_id: 'vord-1001-A',
            meal_id: 'meal-1',
            meal_name_snapshot: 'Smokey Party Jollof Rice with Peppered Chicken',
            unit_price_snapshot: 1800,
            quantity: 1,
            subtotal: 1800,
            image_url: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=600&q=80',
          },
        ],
      },
      {
        id: 'vord-1001-B',
        parent_order_id: 'ord-1001',
        vendor_id: 'vendor-2',
        vendor_name: 'Buka Express',
        status: 'CONFIRMED',
        subtotal: 2500,
        created_at: '2026-08-13T03:15:00Z',
        items: [
          {
            id: 'item-2',
            vendor_order_id: 'vord-1001-B',
            meal_id: 'meal-5',
            meal_name_snapshot: 'Pounded Yam with Rich Egusi Soup & Assorted Meat',
            unit_price_snapshot: 2500,
            quantity: 1,
            subtotal: 2500,
            image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
          },
        ],
      },
    ],
  },
  {
    id: 'ord-1000',
    student_id: 'user-student-1',
    student_name: 'David Ayantade',
    student_phone: '+234 801 234 5678',
    order_reference: 'CB-2026-8902',
    fulfillment_method: 'CAMPUS_PICKUP',
    total_amount: 2200,
    status: 'PICKED_UP',
    created_at: '2026-08-12T14:10:00Z',
    updated_at: '2026-08-12T14:45:00Z',
    completed_at: '2026-08-12T14:45:00Z',
    vendor_orders: [
      {
        id: 'vord-1000-A',
        parent_order_id: 'ord-1000',
        vendor_id: 'vendor-3',
        vendor_name: 'Campus Grills & Shawarma',
        status: 'PICKED_UP',
        subtotal: 2200,
        completed_at: '2026-08-12T14:45:00Z',
        created_at: '2026-08-12T14:10:00Z',
        items: [
          {
            id: 'item-3',
            vendor_order_id: 'vord-1000-A',
            meal_id: 'meal-7',
            meal_name_snapshot: 'Double Sausage Chicken Shawarma + Extra Cheese',
            unit_price_snapshot: 2200,
            quantity: 1,
            subtotal: 2200,
            image_url: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=600&q=80',
          },
        ],
      },
    ],
  },
];

export const INITIAL_STATUS_HISTORY: OrderStatusHistory[] = [
  {
    id: 'hist-1',
    parent_order_id: 'ord-1001',
    vendor_order_id: 'vord-1001-A',
    previous_status: undefined,
    new_status: 'PENDING',
    actor_user_id: 'user-student-1',
    actor_name: 'David Ayantade (Student)',
    note: 'Order submitted by student during checkout.',
    created_at: '2026-08-13T03:15:00Z',
  },
  {
    id: 'hist-2',
    parent_order_id: 'ord-1001',
    vendor_order_id: 'vord-1001-A',
    previous_status: 'PENDING',
    new_status: 'CONFIRMED',
    actor_user_id: 'user-vendor-1',
    actor_name: 'Mama Cass Kitchen',
    note: 'Order accepted by vendor.',
    created_at: '2026-08-13T03:20:00Z',
  },
  {
    id: 'hist-3',
    parent_order_id: 'ord-1001',
    vendor_order_id: 'vord-1001-A',
    previous_status: 'CONFIRMED',
    new_status: 'PREPARING',
    actor_user_id: 'user-vendor-1',
    actor_name: 'Mama Cass Kitchen',
    note: 'Chef started preparing the meal.',
    created_at: '2026-08-13T03:30:00Z',
  },
  {
    id: 'hist-4',
    parent_order_id: 'ord-1001',
    vendor_order_id: 'vord-1001-B',
    previous_status: 'PENDING',
    new_status: 'CONFIRMED',
    actor_user_id: 'user-vendor-2',
    actor_name: 'Buka Express',
    note: 'Order confirmed by Buka Express.',
    created_at: '2026-08-13T03:22:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    recipient_user_id: 'user-student-1',
    type: 'ORDER_STATUS',
    title: 'Order Status Update',
    message: 'Mama Cass Kitchen has started preparing your order #CB-2026-8910.',
    related_order_id: 'ord-1001',
    related_vendor_id: 'vendor-1',
    is_read: false,
    created_at: '2026-08-13T03:30:00Z',
  },
  {
    id: 'notif-2',
    recipient_user_id: 'user-vendor-1',
    type: 'NEW_ORDER',
    title: 'New Order Received!',
    message: 'You have received a new order item under #CB-2026-8910 from David Ayantade.',
    related_order_id: 'ord-1001',
    related_vendor_id: 'vendor-1',
    is_read: true,
    created_at: '2026-08-13T03:15:00Z',
  },
  {
    id: 'notif-3',
    recipient_user_id: 'user-admin-1',
    type: 'VENDOR_VERIFICATION',
    title: 'New Vendor Application Pending',
    message: 'Delight Bakery & Café has submitted an application requiring verification.',
    related_vendor_id: 'vendor-4',
    is_read: false,
    created_at: '2026-08-10T16:20:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    order_id: 'ord-1000',
    order_reference: 'CB-2026-8902',
    student_id: 'user-student-1',
    student_name: 'David Ayantade',
    vendor_id: 'vendor-3',
    vendor_name: 'Campus Grills & Shawarma',
    meal_id: 'meal-7',
    meal_name: 'Double Sausage Chicken Shawarma + Extra Cheese',
    rating: 5,
    comment: 'The shawarma was piping hot, loaded with cheese, and super delicious! Fast pickup service.',
    created_at: '2026-08-12T15:00:00Z',
  },
  {
    id: 'rev-2',
    order_id: 'ord-999',
    order_reference: 'CB-2026-8888',
    student_id: 'user-student-1',
    student_name: 'David Ayantade',
    vendor_id: 'vendor-1',
    vendor_name: 'Mama Cass Kitchen',
    meal_id: 'meal-1',
    meal_name: 'Smokey Party Jollof Rice with Peppered Chicken',
    rating: 5,
    comment: 'Best Jollof on campus! The peppered chicken was tender and spiced just right.',
    created_at: '2026-08-11T18:20:00Z',
  },
  {
    id: 'rev-3',
    order_id: 'ord-998',
    order_reference: 'CB-2026-8875',
    student_id: 'user-student-1',
    student_name: 'David Ayantade',
    vendor_id: 'vendor-2',
    vendor_name: 'Buka Express',
    meal_id: 'meal-5',
    meal_name: 'Pounded Yam with Rich Egusi Soup & Assorted Meat',
    rating: 4,
    comment: 'Pounded yam was soft and smooth. Egusi soup was very rich. Highly recommended!',
    created_at: '2026-08-10T13:45:00Z',
  },
];
